# Generated by Django 2.1.5 on 2024-11-10 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policy_analysis', '0002_auto_20241110_2337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='privacypolicyhistory',
            old_name='date_extracted',
            new_name='date_checked',
        ),
        migrations.RemoveField(
            model_name='privacypolicyhistory',
            name='filename',
        ),
        migrations.RemoveField(
            model_name='privacypolicyhistory',
            name='privacy_policy_text',
        ),
        migrations.AddField(
            model_name='privacypolicyhistory',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='privacypolicyhistory',
            name='policy_text',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='privacypolicyhistory',
            name='similarity_score',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='privacypolicyhistory',
            name='summary',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='trackedsite',
            name='last_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackedsite',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackedsite',
            name='similarity_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackedsite',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='privacypolicyhistory',
            name='tracked_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='policy_analysis.TrackedSite'),
        ),
        migrations.AlterField(
            model_name='trackedsite',
            name='url',
            field=models.URLField(),
        ),
    ]
