# Generated by Django 2.1.5 on 2024-11-11 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_analysis', '0003_auto_20241111_0042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trackedsite',
            old_name='summary',
            new_name='latest_policy',
        ),
        migrations.RemoveField(
            model_name='privacypolicyhistory',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='trackedsite',
            name='similarity_score',
        ),
        migrations.AddField(
            model_name='trackedsite',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='privacypolicyhistory',
            name='policy_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='privacypolicyhistory',
            name='similarity_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='privacypolicyhistory',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trackedsite',
            name='last_updated',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
