# Generated by Django 2.1.5 on 2024-11-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_analysis', '0007_auto_20241111_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackedsite',
            name='last_checked',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
