# Generated by Django 2.1.5 on 2024-11-21 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policy_analysis', '0009_auto_20241121_2234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trackedsite',
            old_name='last_updated',
            new_name='last_checked',
        ),
    ]
