# Generated by Django 2.1.5 on 2024-11-11 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_analysis', '0005_auto_20241111_0858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privacypolicyhistory',
            name='tracked_site',
        ),
        migrations.RemoveField(
            model_name='trackedsite',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='trackedsite',
            name='latest_policy',
        ),
        migrations.AlterField(
            model_name='trackedsite',
            name='last_checked',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='trackedsite',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trackedsite',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='PrivacyPolicyHistory',
        ),
    ]
