# Generated by Django 2.1.5 on 2024-11-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_analysis', '0006_auto_20241111_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackedsite',
            name='extracted_text',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trackedsite',
            name='summarized_text',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
