# Generated by Django 2.1.5 on 2024-11-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_analysis', '0008_auto_20241121_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackedsite',
            name='extracted_text',
        ),
        migrations.RemoveField(
            model_name='trackedsite',
            name='last_checked',
        ),
        migrations.RemoveField(
            model_name='trackedsite',
            name='summarized_text',
        ),
        migrations.AddField(
            model_name='trackedsite',
            name='privacy_policy_extracted',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackedsite',
            name='privacy_policy_last_updated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackedsite',
            name='privacy_policy_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackedsite',
            name='terms_of_service_extracted',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackedsite',
            name='terms_of_service_last_updated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackedsite',
            name='terms_of_service_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
