# Generated by Django 2.1.5 on 2024-12-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_analysis', '0010_auto_20241121_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackedsite',
            name='logourl',
            field=models.URLField(blank=True, null=True),
        ),
    ]
