# Generated by Django 4.2.17 on 2024-12-07 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_analysis', '0013_trackedsite_privacy_policy_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackedsite',
            name='auto_scan_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trackedsite',
            name='last_auto_scan_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
